import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {CATEGORY_NAVBAR} from './api/index'
import {Button,message} from 'antd'
export default function Home() {
    const getData = async () => {
        console.log('1111111111')
        const res = await CATEGORY_NAVBAR()
        console.log(res)
    }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Button type={"primary"} onClick={()=>{getData()}}>2322</Button>
      </div>

    </div>
  )
}
